version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - sharednet

  php:
    build:
      context: ./php
    container_name: php
    volumes:
      - ./src:/var/www/html
    environment:
      - PHP_FPM_LISTEN=9000
    depends_on:
      - postgres
    networks:
      - sharednet

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sharednet

volumes:
  postgres_data:
    driver: local

networks:
  sharednet:
